### YamlMime:ManagedReference
items:
- uid: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig
  commentId: T:Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig
  id: BingSearchConfig
  parent: Microsoft.Toolkit.Uwp.Services.Bing
  children:
  - Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Country
  - Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Language
  - Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Query
  - Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.QueryType
  langs:
  - csharp
  - vb
  name: BingSearchConfig
  nameWithType: BingSearchConfig
  fullName: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig
  type: Class
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/Bing/BingSearchConfig.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: BingSearchConfig
    path: Microsoft.Toolkit.Uwp.Services/Services/Bing/BingSearchConfig.cs
    startLine: 17
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.Bing
  summary: "\nSearch query configuration.\n"
  example: []
  syntax:
    content: public class BingSearchConfig
    content.vb: Public Class BingSearchConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - System.Object.Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Country
  commentId: P:Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Country
  id: Country
  parent: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig
  langs:
  - csharp
  - vb
  name: Country
  nameWithType: BingSearchConfig.Country
  fullName: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Country
  type: Property
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/Bing/BingSearchConfig.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: Country
    path: Microsoft.Toolkit.Uwp.Services/Services/Bing/BingSearchConfig.cs
    startLine: 22
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.Bing
  summary: "\nGets or sets search query country.\n"
  example: []
  syntax:
    content: public BingCountry Country { get; set; }
    parameters: []
    return:
      type: Microsoft.Toolkit.Uwp.Services.Bing.BingCountry
    content.vb: Public Property Country As BingCountry
  overload: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Country*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Language
  commentId: P:Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Language
  id: Language
  parent: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig
  langs:
  - csharp
  - vb
  name: Language
  nameWithType: BingSearchConfig.Language
  fullName: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Language
  type: Property
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/Bing/BingSearchConfig.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: Language
    path: Microsoft.Toolkit.Uwp.Services/Services/Bing/BingSearchConfig.cs
    startLine: 27
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.Bing
  summary: "\nGets or sets search query language.\n"
  example: []
  syntax:
    content: public BingLanguage Language { get; set; }
    parameters: []
    return:
      type: Microsoft.Toolkit.Uwp.Services.Bing.BingLanguage
    content.vb: Public Property Language As BingLanguage
  overload: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Language*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Query
  commentId: P:Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Query
  id: Query
  parent: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig
  langs:
  - csharp
  - vb
  name: Query
  nameWithType: BingSearchConfig.Query
  fullName: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Query
  type: Property
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/Bing/BingSearchConfig.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: Query
    path: Microsoft.Toolkit.Uwp.Services/Services/Bing/BingSearchConfig.cs
    startLine: 32
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.Bing
  summary: "\nGets or sets search query.\n"
  example: []
  syntax:
    content: public string Query { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Query As String
  overload: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Query*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.QueryType
  commentId: P:Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.QueryType
  id: QueryType
  parent: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig
  langs:
  - csharp
  - vb
  name: QueryType
  nameWithType: BingSearchConfig.QueryType
  fullName: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.QueryType
  type: Property
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/Bing/BingSearchConfig.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: QueryType
    path: Microsoft.Toolkit.Uwp.Services/Services/Bing/BingSearchConfig.cs
    startLine: 37
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.Bing
  summary: "\nGets or sets search query type.\n"
  example: []
  syntax:
    content: public BingQueryType QueryType { get; set; }
    parameters: []
    return:
      type: Microsoft.Toolkit.Uwp.Services.Bing.BingQueryType
    content.vb: Public Property QueryType As BingQueryType
  overload: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.QueryType*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Toolkit.Uwp.Services.Bing
  commentId: N:Microsoft.Toolkit.Uwp.Services.Bing
  isExternal: false
  name: Microsoft.Toolkit.Uwp.Services.Bing
  nameWithType: Microsoft.Toolkit.Uwp.Services.Bing
  fullName: Microsoft.Toolkit.Uwp.Services.Bing
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  commentId: M:Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  parent: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods
  definition: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  name: ToSafeString()
  nameWithType: ExtensionMethods.ToSafeString()
  fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString()
  spec.csharp:
  - uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
    name: ToSafeString
    nameWithType: ExtensionMethods.ToSafeString
    fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
    name: ToSafeString
    nameWithType: ExtensionMethods.ToSafeString
    fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  commentId: M:Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  isExternal: true
  name: ToSafeString(Object)
  nameWithType: ExtensionMethods.ToSafeString(Object)
  fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  spec.csharp:
  - uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
    name: ToSafeString
    nameWithType: ExtensionMethods.ToSafeString
    fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
    name: ToSafeString
    nameWithType: ExtensionMethods.ToSafeString
    fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods
  commentId: T:Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods
  parent: Microsoft.Toolkit.Uwp.Services.Core
  isExternal: false
  name: ExtensionMethods
  nameWithType: ExtensionMethods
  fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods
- uid: Microsoft.Toolkit.Uwp.Services.Core
  commentId: N:Microsoft.Toolkit.Uwp.Services.Core
  isExternal: false
  name: Microsoft.Toolkit.Uwp.Services.Core
  nameWithType: Microsoft.Toolkit.Uwp.Services.Core
  fullName: Microsoft.Toolkit.Uwp.Services.Core
- uid: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Country*
  commentId: Overload:Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Country
  isExternal: false
  name: Country
  nameWithType: BingSearchConfig.Country
  fullName: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Country
- uid: Microsoft.Toolkit.Uwp.Services.Bing.BingCountry
  commentId: T:Microsoft.Toolkit.Uwp.Services.Bing.BingCountry
  parent: Microsoft.Toolkit.Uwp.Services.Bing
  isExternal: false
  name: BingCountry
  nameWithType: BingCountry
  fullName: Microsoft.Toolkit.Uwp.Services.Bing.BingCountry
- uid: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Language*
  commentId: Overload:Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Language
  isExternal: false
  name: Language
  nameWithType: BingSearchConfig.Language
  fullName: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Language
- uid: Microsoft.Toolkit.Uwp.Services.Bing.BingLanguage
  commentId: T:Microsoft.Toolkit.Uwp.Services.Bing.BingLanguage
  parent: Microsoft.Toolkit.Uwp.Services.Bing
  isExternal: false
  name: BingLanguage
  nameWithType: BingLanguage
  fullName: Microsoft.Toolkit.Uwp.Services.Bing.BingLanguage
- uid: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Query*
  commentId: Overload:Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Query
  isExternal: false
  name: Query
  nameWithType: BingSearchConfig.Query
  fullName: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.Query
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.QueryType*
  commentId: Overload:Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.QueryType
  isExternal: false
  name: QueryType
  nameWithType: BingSearchConfig.QueryType
  fullName: Microsoft.Toolkit.Uwp.Services.Bing.BingSearchConfig.QueryType
- uid: Microsoft.Toolkit.Uwp.Services.Bing.BingQueryType
  commentId: T:Microsoft.Toolkit.Uwp.Services.Bing.BingQueryType
  parent: Microsoft.Toolkit.Uwp.Services.Bing
  isExternal: false
  name: BingQueryType
  nameWithType: BingQueryType
  fullName: Microsoft.Toolkit.Uwp.Services.Bing.BingQueryType
