### YamlMime:ManagedReference
items:
- uid: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings
  commentId: T:Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings
  id: DiscoverySettings
  parent: Microsoft.Toolkit.Uwp.Services.OneDrive
  children:
  - Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.#ctor
  - Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceEndpointUri
  - Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceResourceId
  langs:
  - csharp
  - vb
  name: DiscoverySettings
  nameWithType: DiscoverySettings
  fullName: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings
  type: Class
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/OneDrive/DiscoverySettings.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: DiscoverySettings
    path: Microsoft.Toolkit.Uwp.Services/Services/OneDrive/DiscoverySettings.cs
    startLine: 19
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.OneDrive
  summary: "\nDiscoverySettings type\n"
  example: []
  syntax:
    content: public class DiscoverySettings
    content.vb: Public Class DiscoverySettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - System.Object.Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceEndpointUri
  commentId: P:Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceEndpointUri
  id: ServiceEndpointUri
  parent: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings
  langs:
  - csharp
  - vb
  name: ServiceEndpointUri
  nameWithType: DiscoverySettings.ServiceEndpointUri
  fullName: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceEndpointUri
  type: Property
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/OneDrive/DiscoverySettings.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: ServiceEndpointUri
    path: Microsoft.Toolkit.Uwp.Services/Services/OneDrive/DiscoverySettings.cs
    startLine: 28
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.OneDrive
  summary: "\nGets or sets the OneDrive For Business&apos;s ServiceEndpoint uri\n"
  example: []
  syntax:
    content: public string ServiceEndpointUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ServiceEndpointUri As String
  overload: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceEndpointUri*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceResourceId
  commentId: P:Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceResourceId
  id: ServiceResourceId
  parent: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings
  langs:
  - csharp
  - vb
  name: ServiceResourceId
  nameWithType: DiscoverySettings.ServiceResourceId
  fullName: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceResourceId
  type: Property
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/OneDrive/DiscoverySettings.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: ServiceResourceId
    path: Microsoft.Toolkit.Uwp.Services/Services/OneDrive/DiscoverySettings.cs
    startLine: 33
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.OneDrive
  summary: "\nGets or sets the OneDrive For Business&apos;s ServiceResourceId\n"
  example: []
  syntax:
    content: public string ServiceResourceId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ServiceResourceId As String
  overload: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceResourceId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.#ctor
  commentId: M:Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.#ctor
  id: '#ctor'
  parent: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings
  langs:
  - csharp
  - vb
  name: DiscoverySettings()
  nameWithType: DiscoverySettings.DiscoverySettings()
  fullName: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.DiscoverySettings()
  type: Constructor
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/OneDrive/DiscoverySettings.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: .ctor
    path: Microsoft.Toolkit.Uwp.Services/Services/OneDrive/DiscoverySettings.cs
    startLine: 43
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.OneDrive
  summary: "\nInitializes a new instance of the <xref href=\"Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings\" data-throw-if-not-resolved=\"false\"></xref> class.\n"
  example: []
  syntax:
    content: public DiscoverySettings()
    content.vb: Public Sub New
  overload: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Toolkit.Uwp.Services.OneDrive
  commentId: N:Microsoft.Toolkit.Uwp.Services.OneDrive
  isExternal: false
  name: Microsoft.Toolkit.Uwp.Services.OneDrive
  nameWithType: Microsoft.Toolkit.Uwp.Services.OneDrive
  fullName: Microsoft.Toolkit.Uwp.Services.OneDrive
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  commentId: M:Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  parent: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods
  definition: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  name: ToSafeString()
  nameWithType: ExtensionMethods.ToSafeString()
  fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString()
  spec.csharp:
  - uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
    name: ToSafeString
    nameWithType: ExtensionMethods.ToSafeString
    fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
    name: ToSafeString
    nameWithType: ExtensionMethods.ToSafeString
    fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  commentId: M:Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  isExternal: true
  name: ToSafeString(Object)
  nameWithType: ExtensionMethods.ToSafeString(Object)
  fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  spec.csharp:
  - uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
    name: ToSafeString
    nameWithType: ExtensionMethods.ToSafeString
    fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
    name: ToSafeString
    nameWithType: ExtensionMethods.ToSafeString
    fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods
  commentId: T:Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods
  parent: Microsoft.Toolkit.Uwp.Services.Core
  isExternal: false
  name: ExtensionMethods
  nameWithType: ExtensionMethods
  fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods
- uid: Microsoft.Toolkit.Uwp.Services.Core
  commentId: N:Microsoft.Toolkit.Uwp.Services.Core
  isExternal: false
  name: Microsoft.Toolkit.Uwp.Services.Core
  nameWithType: Microsoft.Toolkit.Uwp.Services.Core
  fullName: Microsoft.Toolkit.Uwp.Services.Core
- uid: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceEndpointUri*
  commentId: Overload:Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceEndpointUri
  isExternal: false
  name: ServiceEndpointUri
  nameWithType: DiscoverySettings.ServiceEndpointUri
  fullName: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceEndpointUri
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceResourceId*
  commentId: Overload:Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceResourceId
  isExternal: false
  name: ServiceResourceId
  nameWithType: DiscoverySettings.ServiceResourceId
  fullName: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.ServiceResourceId
- uid: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings
  commentId: T:Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings
  isExternal: false
  name: DiscoverySettings
  nameWithType: DiscoverySettings
  fullName: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings
- uid: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.#ctor*
  commentId: Overload:Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.#ctor
  isExternal: false
  name: DiscoverySettings
  nameWithType: DiscoverySettings.DiscoverySettings
  fullName: Microsoft.Toolkit.Uwp.Services.OneDrive.DiscoverySettings.DiscoverySettings
