### YamlMime:ManagedReference
items:
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView
  commentId: T:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView
  id: ApplicationView
  parent: Microsoft.Toolkit.Uwp.UI.Extensions
  children:
  - Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetBackButtonVisibility(Page)
  - Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetExtendViewIntoTitleBar(Page)
  - Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetTitle(Page)
  - Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetBackButtonVisibility(Page,AppViewBackButtonVisibility)
  - Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetExtendViewIntoTitleBar(Page,System.Boolean)
  - Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetTitle(Page,System.String)
  langs:
  - csharp
  - vb
  name: ApplicationView
  nameWithType: ApplicationView
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView
  type: Class
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: ApplicationView
    path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
    startLine: 22
  assemblies:
  - Microsoft.Toolkit.Uwp.UI
  namespace: Microsoft.Toolkit.Uwp.UI.Extensions
  summary: "\nProvides attached properties for interacting with the <see cref=\"!:Windows.UI.ViewManagement.ApplicationView\"></see> on a window (app view).\n"
  example: []
  syntax:
    content: 'public static class ApplicationView : object'
    content.vb: >-
      Public Module ApplicationView

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetTitle(Page)
  commentId: M:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetTitle(Page)
  id: GetTitle(Page)
  parent: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView
  langs:
  - csharp
  - vb
  name: GetTitle(Page)
  nameWithType: ApplicationView.GetTitle(Page)
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetTitle(Page)
  type: Method
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: GetTitle
    path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
    startLine: 29
  assemblies:
  - Microsoft.Toolkit.Uwp.UI
  namespace: Microsoft.Toolkit.Uwp.UI.Extensions
  summary: "\nGets <see cref=\"!:System.String\"></see> for <see cref=\"!:Windows.UI.ViewManagement.ApplicationView.Title\"></see>\n"
  example: []
  syntax:
    content: public static string GetTitle(Page page)
    parameters:
    - id: page
      type: Page
      description: The <see cref="!:Page"></see>
    return:
      type: System.String
      description: <see cref="!:System.String"></see>
    content.vb: Public Shared Function GetTitle(page As Page) As String
  overload: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetTitle*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetTitle(Page,System.String)
  commentId: M:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetTitle(Page,System.String)
  id: SetTitle(Page,System.String)
  parent: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView
  langs:
  - csharp
  - vb
  name: SetTitle(Page, String)
  nameWithType: ApplicationView.SetTitle(Page, String)
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetTitle(Page, System.String)
  type: Method
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: SetTitle
    path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
    startLine: 41
  assemblies:
  - Microsoft.Toolkit.Uwp.UI
  namespace: Microsoft.Toolkit.Uwp.UI.Extensions
  summary: "\nSets <see cref=\"!:System.String\"></see> to <see cref=\"!:Windows.UI.ViewManagement.ApplicationView.Title\"></see>\n"
  example: []
  syntax:
    content: public static void SetTitle(Page page, string value)
    parameters:
    - id: page
      type: Page
      description: The <see cref="!:Page"></see>
    - id: value
      type: System.String
      description: <see cref="!:System.String"></see>
    content.vb: Public Shared Sub SetTitle(page As Page, value As String)
  overload: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetTitle*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetExtendViewIntoTitleBar(Page)
  commentId: M:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetExtendViewIntoTitleBar(Page)
  id: GetExtendViewIntoTitleBar(Page)
  parent: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView
  langs:
  - csharp
  - vb
  name: GetExtendViewIntoTitleBar(Page)
  nameWithType: ApplicationView.GetExtendViewIntoTitleBar(Page)
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetExtendViewIntoTitleBar(Page)
  type: Method
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: GetExtendViewIntoTitleBar
    path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
    startLine: 55
  assemblies:
  - Microsoft.Toolkit.Uwp.UI
  namespace: Microsoft.Toolkit.Uwp.UI.Extensions
  summary: "\nGets <see cref=\"!:System.Boolean\"></see> CoreApplicationView.TitleBar.ExtendViewIntoTitleBar\n"
  example: []
  syntax:
    content: public static bool GetExtendViewIntoTitleBar(Page page)
    parameters:
    - id: page
      type: Page
      description: The <see cref="!:Page"></see>
    return:
      type: System.Boolean
      description: <see cref="!:System.String"></see>
    content.vb: Public Shared Function GetExtendViewIntoTitleBar(page As Page) As Boolean
  overload: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetExtendViewIntoTitleBar*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetExtendViewIntoTitleBar(Page,System.Boolean)
  commentId: M:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetExtendViewIntoTitleBar(Page,System.Boolean)
  id: SetExtendViewIntoTitleBar(Page,System.Boolean)
  parent: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView
  langs:
  - csharp
  - vb
  name: SetExtendViewIntoTitleBar(Page, Boolean)
  nameWithType: ApplicationView.SetExtendViewIntoTitleBar(Page, Boolean)
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetExtendViewIntoTitleBar(Page, System.Boolean)
  type: Method
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: SetExtendViewIntoTitleBar
    path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
    startLine: 67
  assemblies:
  - Microsoft.Toolkit.Uwp.UI
  namespace: Microsoft.Toolkit.Uwp.UI.Extensions
  summary: "\nSets <see cref=\"!:System.Boolean\"></see> to CoreApplicationView.TitleBar.ExtendViewIntoTitleBar\n"
  example: []
  syntax:
    content: public static void SetExtendViewIntoTitleBar(Page page, bool value)
    parameters:
    - id: page
      type: Page
      description: The <see cref="!:Page"></see>
    - id: value
      type: System.Boolean
      description: <see cref="!:System.Boolean"></see>
    content.vb: Public Shared Sub SetExtendViewIntoTitleBar(page As Page, value As Boolean)
  overload: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetExtendViewIntoTitleBar*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetBackButtonVisibility(Page)
  commentId: M:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetBackButtonVisibility(Page)
  id: GetBackButtonVisibility(Page)
  parent: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView
  langs:
  - csharp
  - vb
  name: GetBackButtonVisibility(Page)
  nameWithType: ApplicationView.GetBackButtonVisibility(Page)
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetBackButtonVisibility(Page)
  type: Method
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: GetBackButtonVisibility
    path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
    startLine: 81
  assemblies:
  - Microsoft.Toolkit.Uwp.UI
  namespace: Microsoft.Toolkit.Uwp.UI.Extensions
  summary: "\nGets <see cref=\"!:AppViewBackButtonVisibility\"></see> for <see cref=\"!:SystemNavigationManager.AppViewBackButtonVisibility\"></see>\n"
  example: []
  syntax:
    content: public static AppViewBackButtonVisibility GetBackButtonVisibility(Page page)
    parameters:
    - id: page
      type: Page
      description: The <see cref="!:Page"></see>
    return:
      type: AppViewBackButtonVisibility
      description: <see cref="!:System.String"></see>
    content.vb: Public Shared Function GetBackButtonVisibility(page As Page) As AppViewBackButtonVisibility
  overload: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetBackButtonVisibility*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetBackButtonVisibility(Page,AppViewBackButtonVisibility)
  commentId: M:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetBackButtonVisibility(Page,AppViewBackButtonVisibility)
  id: SetBackButtonVisibility(Page,AppViewBackButtonVisibility)
  parent: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView
  langs:
  - csharp
  - vb
  name: SetBackButtonVisibility(Page, AppViewBackButtonVisibility)
  nameWithType: ApplicationView.SetBackButtonVisibility(Page, AppViewBackButtonVisibility)
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetBackButtonVisibility(Page, AppViewBackButtonVisibility)
  type: Method
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: SetBackButtonVisibility
    path: Microsoft.Toolkit.Uwp.UI/Extensions/ApplicationView/ApplicationView.cs
    startLine: 93
  assemblies:
  - Microsoft.Toolkit.Uwp.UI
  namespace: Microsoft.Toolkit.Uwp.UI.Extensions
  summary: "\nSets <see cref=\"!:AppViewBackButtonVisibility\"></see> to <see cref=\"!:SystemNavigationManager.AppViewBackButtonVisibility\"></see>\n"
  example: []
  syntax:
    content: public static void SetBackButtonVisibility(Page page, AppViewBackButtonVisibility value)
    parameters:
    - id: page
      type: Page
      description: The <see cref="!:Page"></see>
    - id: value
      type: AppViewBackButtonVisibility
      description: <see cref="!:AppViewBackButtonVisibility"></see>
    content.vb: Public Shared Sub SetBackButtonVisibility(page As Page, value As AppViewBackButtonVisibility)
  overload: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetBackButtonVisibility*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Microsoft.Toolkit.Uwp.UI.Extensions
  commentId: N:Microsoft.Toolkit.Uwp.UI.Extensions
  isExternal: false
  name: Microsoft.Toolkit.Uwp.UI.Extensions
  nameWithType: Microsoft.Toolkit.Uwp.UI.Extensions
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetTitle*
  commentId: Overload:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetTitle
  isExternal: false
  name: GetTitle
  nameWithType: ApplicationView.GetTitle
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetTitle
- uid: Page
  isExternal: true
  name: Page
  nameWithType: Page
  fullName: Page
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetTitle*
  commentId: Overload:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetTitle
  isExternal: false
  name: SetTitle
  nameWithType: ApplicationView.SetTitle
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetTitle
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetExtendViewIntoTitleBar*
  commentId: Overload:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetExtendViewIntoTitleBar
  isExternal: false
  name: GetExtendViewIntoTitleBar
  nameWithType: ApplicationView.GetExtendViewIntoTitleBar
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetExtendViewIntoTitleBar
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetExtendViewIntoTitleBar*
  commentId: Overload:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetExtendViewIntoTitleBar
  isExternal: false
  name: SetExtendViewIntoTitleBar
  nameWithType: ApplicationView.SetExtendViewIntoTitleBar
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetExtendViewIntoTitleBar
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetBackButtonVisibility*
  commentId: Overload:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetBackButtonVisibility
  isExternal: false
  name: GetBackButtonVisibility
  nameWithType: ApplicationView.GetBackButtonVisibility
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.GetBackButtonVisibility
- uid: AppViewBackButtonVisibility
  isExternal: true
  name: AppViewBackButtonVisibility
  nameWithType: AppViewBackButtonVisibility
  fullName: AppViewBackButtonVisibility
- uid: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetBackButtonVisibility*
  commentId: Overload:Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetBackButtonVisibility
  isExternal: false
  name: SetBackButtonVisibility
  nameWithType: ApplicationView.SetBackButtonVisibility
  fullName: Microsoft.Toolkit.Uwp.UI.Extensions.ApplicationView.SetBackButtonVisibility
