### YamlMime:ManagedReference
items:
- uid: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
  commentId: T:Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
  id: FacebookDataConfig
  parent: Microsoft.Toolkit.Uwp.Services.Facebook
  children:
  - Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyFeed
  - Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyPosts
  - Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyTagged
  - Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.Query
  langs:
  - csharp
  - vb
  name: FacebookDataConfig
  nameWithType: FacebookDataConfig
  fullName: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
  type: Class
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookDataConfig.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: FacebookDataConfig
    path: Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookDataConfig.cs
    startLine: 17
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.Facebook
  summary: "\nConfiguration object for specifying richer query information.\n"
  example: []
  syntax:
    content: public class FacebookDataConfig
    content.vb: Public Class FacebookDataConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - System.Object.Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyFeed
  commentId: P:Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyFeed
  id: MyFeed
  parent: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
  langs:
  - csharp
  - vb
  name: MyFeed
  nameWithType: FacebookDataConfig.MyFeed
  fullName: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyFeed
  type: Property
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookDataConfig.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: MyFeed
    path: Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookDataConfig.cs
    startLine: 22
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.Facebook
  summary: "\nGets a predefined config to get user feed. The feed of posts (including status updates) and links published by this person, or by others on this person&apos;s profile\n"
  example: []
  syntax:
    content: public static FacebookDataConfig MyFeed { get; }
    parameters: []
    return:
      type: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
    content.vb: Public Shared ReadOnly Property MyFeed As FacebookDataConfig
  overload: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyFeed*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyPosts
  commentId: P:Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyPosts
  id: MyPosts
  parent: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
  langs:
  - csharp
  - vb
  name: MyPosts
  nameWithType: FacebookDataConfig.MyPosts
  fullName: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyPosts
  type: Property
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookDataConfig.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: MyPosts
    path: Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookDataConfig.cs
    startLine: 27
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.Facebook
  summary: "\nGets a predefined config to show only the posts that were published by this person\n"
  example: []
  syntax:
    content: public static FacebookDataConfig MyPosts { get; }
    parameters: []
    return:
      type: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
    content.vb: Public Shared ReadOnly Property MyPosts As FacebookDataConfig
  overload: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyPosts*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyTagged
  commentId: P:Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyTagged
  id: MyTagged
  parent: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
  langs:
  - csharp
  - vb
  name: MyTagged
  nameWithType: FacebookDataConfig.MyTagged
  fullName: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyTagged
  type: Property
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookDataConfig.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: MyTagged
    path: Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookDataConfig.cs
    startLine: 32
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.Facebook
  summary: "\nGets a predefined config to show only the posts that this person was tagged in\n"
  example: []
  syntax:
    content: public static FacebookDataConfig MyTagged { get; }
    parameters: []
    return:
      type: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
    content.vb: Public Shared ReadOnly Property MyTagged As FacebookDataConfig
  overload: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyTagged*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.Query
  commentId: P:Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.Query
  id: Query
  parent: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
  langs:
  - csharp
  - vb
  name: Query
  nameWithType: FacebookDataConfig.Query
  fullName: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.Query
  type: Property
  source:
    remote:
      path: Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookDataConfig.cs
      branch: docfx
      repo: https://github.com/Microsoft/UWPCommunityToolkit.git
    id: Query
    path: Microsoft.Toolkit.Uwp.Services/Services/Facebook/FacebookDataConfig.cs
    startLine: 37
  assemblies:
  - Microsoft.Toolkit.Uwp.Services
  namespace: Microsoft.Toolkit.Uwp.Services.Facebook
  summary: "\nGets or sets the query string for filtering service results.\n"
  example: []
  syntax:
    content: public string Query { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Query As String
  overload: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.Query*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Toolkit.Uwp.Services.Facebook
  commentId: N:Microsoft.Toolkit.Uwp.Services.Facebook
  isExternal: false
  name: Microsoft.Toolkit.Uwp.Services.Facebook
  nameWithType: Microsoft.Toolkit.Uwp.Services.Facebook
  fullName: Microsoft.Toolkit.Uwp.Services.Facebook
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  commentId: M:Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  parent: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods
  definition: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  name: ToSafeString()
  nameWithType: ExtensionMethods.ToSafeString()
  fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString()
  spec.csharp:
  - uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
    name: ToSafeString
    nameWithType: ExtensionMethods.ToSafeString
    fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
    name: ToSafeString
    nameWithType: ExtensionMethods.ToSafeString
    fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  commentId: M:Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  isExternal: true
  name: ToSafeString(Object)
  nameWithType: ExtensionMethods.ToSafeString(Object)
  fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
  spec.csharp:
  - uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
    name: ToSafeString
    nameWithType: ExtensionMethods.ToSafeString
    fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString(System.Object)
    name: ToSafeString
    nameWithType: ExtensionMethods.ToSafeString
    fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods.ToSafeString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods
  commentId: T:Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods
  parent: Microsoft.Toolkit.Uwp.Services.Core
  isExternal: false
  name: ExtensionMethods
  nameWithType: ExtensionMethods
  fullName: Microsoft.Toolkit.Uwp.Services.Core.ExtensionMethods
- uid: Microsoft.Toolkit.Uwp.Services.Core
  commentId: N:Microsoft.Toolkit.Uwp.Services.Core
  isExternal: false
  name: Microsoft.Toolkit.Uwp.Services.Core
  nameWithType: Microsoft.Toolkit.Uwp.Services.Core
  fullName: Microsoft.Toolkit.Uwp.Services.Core
- uid: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyFeed*
  commentId: Overload:Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyFeed
  isExternal: false
  name: MyFeed
  nameWithType: FacebookDataConfig.MyFeed
  fullName: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyFeed
- uid: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
  commentId: T:Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
  parent: Microsoft.Toolkit.Uwp.Services.Facebook
  isExternal: false
  name: FacebookDataConfig
  nameWithType: FacebookDataConfig
  fullName: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig
- uid: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyPosts*
  commentId: Overload:Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyPosts
  isExternal: false
  name: MyPosts
  nameWithType: FacebookDataConfig.MyPosts
  fullName: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyPosts
- uid: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyTagged*
  commentId: Overload:Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyTagged
  isExternal: false
  name: MyTagged
  nameWithType: FacebookDataConfig.MyTagged
  fullName: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.MyTagged
- uid: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.Query*
  commentId: Overload:Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.Query
  isExternal: false
  name: Query
  nameWithType: FacebookDataConfig.Query
  fullName: Microsoft.Toolkit.Uwp.Services.Facebook.FacebookDataConfig.Query
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
